apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sRestrictNamespaces
metadata:
  name: restrict-default-ns
spec:
  match:
      kinds:
        - apiGroups:
            - ''
          kinds:
            - Pod
  enforcementAction: deny
  parameters:
    restrictedNamespaces:
    - default
