namespace: team-a

resources:
- ../base
- ../../all-clusters/team-a

namePrefix: team-a-

helmCharts:
- name: prometheus
  repo: https://prometheus-community.github.io/helm-charts
  version: v15.8.5
  releaseName: my-prometheus

patches:
- target:
    kind: Namespace
    name: default
  patch: |-
    - op: replace
      path: /metadata/name
      value: team-a
