apiVersion: templates.gatekeeper.sh/v1
kind: ConstraintTemplate
metadata:
  annotations:
    description: Restricts resources from using namespaces listed under the restrictedNamespaces
      parameter.
  name: k8srestrictnamespaces
  namespace: security
spec:
  crd:
    spec:
      names:
        kind: K8sRestrictNamespaces
      validation:
        legacySchema: true
        openAPIV3Schema:
          properties:
            restrictedNamespaces:
              description: A list of Namespaces to restrict.
              items:
                type: string
              type: array
  targets:
  - rego: |
      package k8srestrictnamespaces

      violation[{"msg": msg}] {
        restricted_ns := input.parameters.restrictedNamespaces[_]
        input.review.object.metadata.namespace == restricted_ns
        msg := sprintf("<%v> namespace is restricted", [restricted_ns])
      }
    target: admission.k8s.gatekeeper.sh
