apiVersion: v1
kind: Pod
metadata:
  name: all-present-pod
spec:
  containers:
  - name: ubuntu
    image: ubuntu
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "apt update -y; apt install iputils-ping -y; while true; do sleep 30; done;" ]
